dist: xenial
language: python
python: 3.7
env:
  - DJANGO_SETTINGS_MODULE=config.settings.dev
install:
  - pip3 install -r requirements/test.txt
before_script:
  - python3 src/manage.py migrate
script:
  - python3 src/manage.py test
after_success: coverage run --source='src/.' src/manage.py test
